import { useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import {
  Home, ListChecks, Layers, FileType, Shield,
  ChevronDown, AlertCircle, Lock, CreditCard, Scale, ShieldAlert, RefreshCw
} from 'lucide-react';
import NavBar from './NavBar';

const CATEGORY_ICONS = [Lock, Scale, CreditCard, FileType, RefreshCw];

const RISK_PILL = {
  Low: 'bg-[#E8F3EC] text-[#2F855A]',
  Medium: 'bg-[#FDF3E4] text-[#DD6B20]',
  High: 'bg-[#FDEAEA] text-[#E53E3E]',
};

function ResultsPage() {
  const location = useLocation();
  const navigate = useNavigate();
  const [openFlags, setOpenFlags] = useState({});
  const [openTerm, setOpenTerm] = useState(null);

  const result = location.state?.result;

  if (!result) {
    return (
      <div className="min-h-screen bg-[#F7F5F0] flex items-center justify-center px-6">
        <div className="text-center">
          <p className="mb-4 text-gray-600">No results to show — try analyzing something first.</p>
          <button
            onClick={() => navigate('/')}
            className="bg-[#1B4332] text-white font-bold px-6 py-3 rounded-md"
          >
            Go back
          </button>
        </div>
      </div>
    );
  }

  const riskPillClass = RISK_PILL[result.risk_level] || RISK_PILL.Medium;

  const downloadMarkdown = () => {
    let md = `# Terms & Conditions Summary\n\n`;
    md += `**Risk Level:** ${result.risk_level}\n\n`;
    md += `${result.verdict}\n\n`;

    md += `## Red Flags\n`;
    (result.red_flags || []).forEach(f => { md += `- ${f}\n`; });

    md += `\n## Summary by Category\n`;
    (result.categories || []).forEach(c => {
      md += `\n**${c.name}**\n${c.summary}\n`;
    });

    if ((result.clauses || []).length > 0) {
      md += `\n## Original Clause → Plain English\n`;
      result.clauses.forEach(c => {
        md += `\n> "${c.original}"\n\n${c.plain}\n`;
      });
    }

    if ((result.legal_terms || []).length > 0) {
      md += `\n## Legal Terms Glossary\n`;
      result.legal_terms.forEach(t => {
        md += `- **${t.term}**: ${t.definition}\n`;
      });
    }

    md += `\n---\n*Generated by Fine Print — not legal advice.*\n`;

    const blob = new Blob([md], { type: 'text/markdown' });
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = 'terms-summary.md';
    link.click();
  };

  const toggleFlag = (i) => setOpenFlags(prev => ({ ...prev, [i]: !prev[i] }));

  const scrollTo = (id) => {
    document.getElementById(id)?.scrollIntoView({ behavior: 'smooth', block: 'start' });
  };

  return (
    <div className="min-h-screen bg-[#F7F5F0]">
      <NavBar
        variant="results"
        onNewAnalysis={() => navigate('/')}
        onDownload={downloadMarkdown}
      />

      <div className="max-w-6xl mx-auto px-4 sm:px-8 py-8 flex gap-8">

        {/* Sidebar */}
        <div className="hidden md:block w-48 flex-shrink-0">
          <div className="sticky top-8 space-y-1">
            <button onClick={() => scrollTo('overview')} className="w-full flex items-center gap-2 text-sm text-[#1B4332] font-medium bg-[#E8F3EC] rounded-md px-3 py-2">
              <Home size={14} /> Overview
            </button>
            <button onClick={() => scrollTo('findings')} className="w-full flex items-center gap-2 text-sm text-gray-500 hover:bg-[#F3F1EA] rounded-md px-3 py-2">
              <ListChecks size={14} /> Key Findings
            </button>
            <button onClick={() => scrollTo('breakdown')} className="w-full flex items-center gap-2 text-sm text-gray-500 hover:bg-[#F3F1EA] rounded-md px-3 py-2">
              <Layers size={14} /> Breakdown
            </button>
            {(result.clauses || []).length > 0 && (
              <button onClick={() => scrollTo('original')} className="w-full flex items-center gap-2 text-sm text-gray-500 hover:bg-[#F3F1EA] rounded-md px-3 py-2">
                <FileType size={14} /> Original Text
              </button>
            )}
          </div>
        </div>

        {/* Main content */}
        <div className="flex-1 space-y-6 max-w-2xl">

          <div>
            <h1 className="font-serif text-2xl text-[#1B4332] mb-1">Analysis Results</h1>
            <p className="text-sm text-gray-500">Here's what we found in your document.</p>
          </div>

          {/* Overview card */}
          <div id="overview" className="bg-white rounded-xl border border-[#E5E1D8] p-6 scroll-mt-8">
            <div className="flex gap-4">
              <div className={`w-12 h-12 rounded-lg flex items-center justify-center flex-shrink-0 ${riskPillClass}`}>
                <Shield size={22} />
              </div>
              <div>
                <p className="text-xs uppercase tracking-wide text-gray-400 mb-1">Overall read</p>
                <p className={`font-serif text-xl font-bold mb-2 ${riskPillClass.split(' ')[1]}`}>
                  {result.risk_level} Risk
                </p>
                <p className="text-sm text-gray-600 leading-relaxed">{result.verdict}</p>
              </div>
            </div>
          </div>

          {result.confidence_note && (
            <div className="bg-[#E9F1FB] text-[#2C5282] text-sm p-4 rounded-xl">
              <strong>Note:</strong> {result.confidence_note}
            </div>
          )}

          {result.was_truncated && (
            <div className="bg-[#FDF3E4] text-[#8A6D14] text-sm p-4 rounded-xl">
              This document was very long ({result.original_length?.toLocaleString()} characters) — only the first part was analyzed.
            </div>
          )}

          {/* Findings (accordion) */}
          <div id="findings" className="bg-white rounded-xl border border-[#E5E1D8] p-6 scroll-mt-8">
            <p className="text-xs font-bold uppercase tracking-widest text-gray-500 mb-4">Worth a second look</p>
            <div className="space-y-1">
              {(result.red_flags || []).map((f, i) => (
                <div key={i} className="border-b border-[#F0EDE4] last:border-none">
                  <button
                    onClick={() => toggleFlag(i)}
                    className="w-full flex items-center gap-3 py-3 text-left"
                  >
                    <AlertCircle size={16} className="text-[#E53E3E] flex-shrink-0" />
                    <span className="text-sm flex-1">{f}</span>
                    <ChevronDown
                      size={16}
                      className={`text-gray-400 transition-transform flex-shrink-0 ${openFlags[i] ? 'rotate-180' : ''}`}
                    />
                  </button>
                </div>
              ))}
            </div>
          </div>

          {/* Categories */}
          <div id="breakdown" className="scroll-mt-8">
            <p className="text-xs font-bold uppercase tracking-widest text-gray-500 mb-4">Summary by category</p>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              {(result.categories || []).map((c, i) => {
                const Icon = CATEGORY_ICONS[i % CATEGORY_ICONS.length];
                return (
                  <div key={i} className="bg-white rounded-xl border border-[#E5E1D8] p-5">
                    <div className="flex items-center justify-between mb-3">
                      <div className="w-8 h-8 rounded-md bg-[#F3F1EA] flex items-center justify-center">
                        <Icon size={15} className="text-[#1B4332]" />
                      </div>
                      <span className={`text-[10px] font-bold uppercase px-2 py-1 rounded-full ${riskPillClass}`}>
                        {result.risk_level} Risk
                      </span>
                    </div>
                    <h3 className="text-sm font-semibold text-[#1B4332] mb-1">{c.name}</h3>
                    <p className="text-xs text-gray-500 leading-relaxed">{c.summary}</p>
                  </div>
                );
              })}
            </div>
          </div>

          {/* Clauses */}
          {(result.clauses || []).length > 0 && (
            <div id="original" className="bg-white rounded-xl border border-[#E5E1D8] p-6 scroll-mt-8">
              <p className="text-xs font-bold uppercase tracking-widest text-gray-500 mb-4">Original clause → plain English</p>
              <div className="space-y-5">
                {result.clauses.map((c, i) => (
                  <div key={i} className="grid grid-cols-1 sm:grid-cols-2 gap-4 pb-5 border-b border-[#F0EDE4] last:border-none">
                    <p className="text-xs italic text-gray-500 leading-relaxed">"{c.original}"</p>
                    <p className="text-xs text-[#1B4332] leading-relaxed">{c.plain}</p>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Glossary */}
          {(result.legal_terms || []).length > 0 && (
            <div className="bg-white rounded-xl border border-[#E5E1D8] p-6">
              <p className="text-xs font-bold uppercase tracking-widest text-gray-500 mb-4">Legal jargon, highlighted</p>
              <div className="flex flex-wrap gap-2">
               {result.legal_terms.map((t, i) => (
               <div key={i} className="relative">
               <button
               onClick={() => setOpenTerm(openTerm === i ? null : i)}
               className="text-xs bg-[#F3F1EA] text-[#1B4332] px-3 py-1.5 rounded-full cursor-pointer"
               >
               {t.term}
              </button>
              {openTerm === i && (
              <div className="absolute bottom-full left-0 mb-2 w-56 bg-[#1B4332] text-white text-xs p-3 rounded-lg shadow-lg z-10">
              {t.definition}
              </div>
               )}
             </div>
             ))}
              </div>
            </div>
          )}

          <p className="text-xs text-gray-400 text-center pt-4">
            AI analysis is for informational purposes only and not legal advice.
          </p>
        </div>
      </div>
    </div>
  );
}

export default ResultsPage;